version: '3.8'
services:
  jenkins:
    image: registry.cn-hangzhou.aliyuncs.com/smartide/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    environment:
        JAVA_OPTS: -Djenkins.install.runSetupWizard=false
    volumes:
      - /home/smartide/jenkins/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    